version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@H8JB76RDSP034DEM_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=duoc_fullstack
      - spring.datasource.password="Eduardocr#2610"
    restart: always